# Generated by Django 5.1.2 on 2024-10-22 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_imagetag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
    ]
