# Generated by Django 5.1.2 on 2024-10-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_image_tags_delete_imagetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.ImageField(default=3, upload_to='images'),
            preserve_default=False,
        ),
    ]
